# Generated by Django 4.1.4 on 2023-06-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_mobile', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacies',
            fields=[
                ('pharmacy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=50)),
                ('pharmacy_address', models.CharField(max_length=50)),
                ('pharmacy_image', models.ImageField(upload_to='images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_time', models.TimeField()),
                ('bus_date', models.DateField()),
                ('bus_from', models.CharField(max_length=50)),
                ('bus_to', models.CharField(max_length=50)),
                ('bus_image', models.ImageField(upload_to='images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
