# Generated by Django 4.1.4 on 2023-07-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pharmacies',
            name='pharmacy_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
